
import localFont from "next/font/local";
import "./globals.css";
import ClientSessionProvider from '../components/ClientSessionProvider';
import { Metadata } from 'next';

export const metadata = {
  title: 'Maligai Saman list PDF Generator ',
  description: 'Create and manage your maligai saman list with our efficient app. Generate PDF grocery lists in Tamil and English. Perfect for monthly maligai kadai shopping. Easy-to-use maligai saman list maker for all your grocery needs.',
  keywords: ['maligai list in english','maligai list in tamil','maligai saman list pdf','grocery list pdf generator','grocery', 'maligai saman list in tamil app', 'monthly maligai saman list in tamil pdf', 'maligai kadai saman list'],
  openGraph: {
    title: 'Maligai Saman list PDF Generator',
    description: 'Create and manage your maligai saman list with our efficient app. Generate PDF grocery lists in Tamil and English. Perfect for monthly maligai kadai shopping. Easy-to-use maligai saman list maker for all your grocery needs.',
    url: 'https://yourdomain.com',
    siteName: 'Maligai Saman list in Tamil PDF Generator',
    images: [
      {
        url: 'https://yourdomain.com/og-image.jpg',
        width: 1200,
        height: 630,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  youtube: {
    title: 'Maligai Saman List PDF Generator: Easy Grocery Planning in Tamil & English',
    description: 'Simplify your grocery shopping with our Maligai Saman List app! Create, manage, and generate PDF grocery lists in Tamil and English. Perfect for monthly maligai kadai shopping. Download now and make your grocery planning effortless!',
    channelId: 'YOUR_YOUTUBE_CHANNEL_ID',
    videoId: 'YOUR_VIDEO_ID', // If you have a specific video about the app
    tags: [
      'maligai saman list',
      'maligai list app',
      'Tamil grocery list',
      'English grocery list',
      'maligai list PDF generator',
      'maligai kadai shopping',
      'maligai budget app',
      'maligai saman budget planner'
    ]
  }
};


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       {/* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */}
      <body>
      <ClientSessionProvider>{children}</ClientSessionProvider>
      </body>
    </html>
  );
}
